#!/usr/bin/env python3
"""
Copyright © 2023 Eli Array Minkoff
Permission to use, copy, modify, and/or distribute this software for
any purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL
WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY
DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT
OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
"""

import sys
import re

esc_extract_str = "\x1b(\\[[0-9;]*m)"
esc_styling_str = "\x1b[1;93m^[\x1b[0;91m\\1\x1b[0m"


if sys.argv[1:]:
    for fname in sys.argv[1:]:
        with open(fname) as f:
            print(re.sub(esc_extract_str, esc_styling_str, f.read()), end="")


else:
    for line_text in sys.stdin.readlines():
        print(re.sub(esc_extract_str, esc_styling_str, line_text), end="")
