#!/bin/sh

# Copyright © 2023 Eli Array Minkoff
# SPDX-FileCopyrightText: 2023 Eli Array Minkoff
#
# SPDX-License-Identifier: 0BSD

if [ "$(id -u)" -ne 0 ]; then
    printf 'Error: spipx must be run as root!\n'
fi

PIPX_HOME=/opt/pipx PIPX_BIN=/opt/pipx/bin pipx "$@"
